---
title: "hw02_gap_dplyr"
author: "Avril Metcalfe-Roach"
date: "18 September 2019"
output: github_document
---

```{r libraries, warning=FALSE, include=FALSE}
library(dplyr)
library(tidyverse)
library(gapminder)
```

# Exercise 1: Dplyr package

## Data Initialization
```{r as_tibble}
raw_data <- gapminder %>% 
  as_tibble()
```


## 1.1 - Subset gapminder to 3 countries, 1970s.
### Countries: Canada, India, Italy
```{r 1.1}
filtered <- raw_data %>% 
  filter(country %in% c("Canada","India","Italy"), 
         year %in% c(1970:1979))
```

## 1.2 - Select country, gdpPercap using %>%
```{r 1.2}
country_gdp <- filtered %>% 
  select(country,gdpPercap)
country_gdp
```

## 1.3 - Countries with drops in life expectancy
```{r 1.3}
exp_list <- gapminder$lifeExp
change <- diff(exp_list,lag=1,differences=1)
# Add NA value to beginning of change vector:
change_2 <- append(change,NA,after=0)
# Create new tibble with delta life expectancy as a column:
gapminder_lifeExp <- gapminder
gapminder_lifeExp$delta <- change_2

# NOTE: INCLUDES APPARENT REDUCTIONS IN LIFE EXP DUE TO SWITCHING COUNTRIES!!!
gapminder_redExp <- gapminder_lifeExp %>% 
  filter(delta < 0)
```

## 1.4 - Gapminder: max GDP per capita per country
```{r 1.4}
# Create new column that lists the max GDP per country
gap_max_gdp <- gapminder %>% 
  group_by(country) %>% 
  mutate(max_gdp = max(gdpPercap)) %>% 
  ungroup()

# Filters gapminder to only show max GDP; removes the redundant 'max GDP' column
max_per_country <- gap_max_gdp %>% 
  filter(gdpPercap == max_gdp) %>% 
  subset(select = -max_gdp)
```


