---
title: "hw03_2"
author: "Avril Metcalfe-Roach"
date: "9/29/2019"
output: 
  html_document:
    keep_md: true
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages, include = FALSE, warning=FALSE}
library(gapminder)
library(tidyverse)
library(ggplot2)
library(knitr)
library(kableExtra)
library(formattable)
library(scales)
```

# Task Option 5: Life Expectancy over Time, Per Continent
The gapminder dataset was used to identify how life expectancy has changed over time, on a per-continent basis.
```{r o5}
o5 <- gapminder %>% 
  group_by(continent,year) %>% 
  summarize(`Avg Life Exp` = mean(lifeExp),
            `Std Dev Life Exp` = sd(lifeExp)) %>% 
  rename("Continent"=continent, "Year" = year)
o5$`Avg Life Exp` <- round(o5$`Avg Life Exp`,1)
o5$`Std Dev Life Exp` <- round(o5$`Std Dev Life Exp`,1)
o5
```


```{r o5_plot}
o5 %>% 
  ggplot(aes(Year, `Avg Life Exp`, 
             group = Continent, 
             colour = Continent)) +
  geom_line(size = 1) +
  geom_point() +
  geom_errorbar(aes(ymin = `Avg Life Exp` - `Std Dev Life Exp`,
                    ymax = `Avg Life Exp` + `Std Dev Life Exp`), 
                size = 0.75, position=position_dodge(0.05)) +
  ggtitle("Change in Life Expectancy Per Continent") +
  theme_classic()
```
<!-- Error bars: http://www.sthda.com/english/wiki/ggplot2-error-bars-quick-start-guide-r-software-and-data-visualization-->

